---
author: "Matti Vuorre"
date: 2014-10-11
title: "Passive eye movements go unnoticed"
categories: ["psychology"]
tags: ["review"]
description: "Everything was better in the sixties"
---

What happens when the eye is passively dislocated? Well, it turns out that the research on that is out (or rather has been out since 1960), and the answer is very strange indeed.

[Brindley and Merton](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC1359735/), writing in 1960 in the Journal of Physiology reported that when the human eye is moved passively with a special contact lens, while the muscles usually responsible of the movement of the eye are anaesthetized, that people were unaware that their eye has moved. In one of their experiments (with one subject), a subject was asked to move his eyes freely, while the eyes were actually *held firmly in place with forceps*, and then report what he experienced. The subject reported movement of the visual world, suggesting that the mechanism that adjusts for the movement of the eyes---to stabilize visual perception---in fact adjusts to *intentions*, not actual eye movements. This is bizarre, and should certainly be a focus of more research. It is certainly provocative to think of this phenomenon in terms of the recently popularized accounts of [cognition as prediction](http://ukcatalogue.oup.com/product/9780199686735.do).

Their methods:  

>One conjunctival sac was anaesthetized with cocaine [...] During [active movements] both eyes were held firmly with forceps [...] An assistant held the lids of both eyes widely open[.]

Awesome.
