---
title: On bayesian data analysis and bayes factors
author: Matti Vuorre
date: '2017-05-03'
slug: bayes-is-bayes-isnt
categories:
  - statistics
tags:
  - bayes
  - research methods
draft: no
output:
  blogdown::html_page:
    toc: true
    number_sections: true
    toc_depth: 1
summary: "It appears that there is an imbalance in what many beginning bayesian data analysts think about BDA. From casual observation and discussions, I've noticed a tendency for people to equate bayesian methods with computing bayes factors; that is, testing (usually null) hypotheses using bayesian model comparison."
---

There's a lot of buzz around bayesian data analysis (BDA) in psychology blogs, social media, and journal articles. For instance, in 2015 the APS Observer ran three columns dedicated to BDA in consecutive issues of the journal (Gallistel, 2015a, b, & c), and browsing the latest issues of Psychonomic Bulletin and Review gives an impression of increased interest in the topic. 

# Bayesian data analysis is more than bayes factors

However, it appears that there is an imbalance in what many beginning bayesian data analysts think about BDA. From casual observation and discussions, I've noticed a tendency for people to equate bayesian methods with computing bayes factors; that is, testing (usually null) hypotheses using bayesian model comparison.
    
I don't have good data on people's impressions of what BDA is, but here's another anecdote. At a recent [conference on Bayesian statistics](http://www.maths.lu.se/bayeslund2017/) [Mark Andrews](https://twitter.com/xmjandrews) [summarized his experiences](https://youtu.be/_gAg9UG9RCA) teaching BDA workshops for social scientists. The talk was quite interesting, and what particularly picked my curiosity was his comment that for many--if not most--workshop participants, bayesian data analysis meant hypothesis testing with bayes factors (at 20 minutes in the linked video). (As an aside, he also noted that Stan has now superseded JAGS and BUGS as the preferred choice for a probabilistic modeling language. Go Stan!)

This imbalance or conflation of bayes factors and bayesian data analysis (if it is real and not merely bias in my observations!) is quite disappointing because BDA is a vast field of awesome methods, and bayes factors (BF) are only one thing that you can do with it[^note]. In fact, many textbooks on BDA mention BFs only in footnotes (Gelman et al., 2013; McElreath, 2016). I've also written about BDA on my blog about a half-dozen times, but only once about bayes factors (Vuorre, 2016). 

Further, it is really only this one method that people bicker over on social media: the bayes vs. frequentism argument usually turns into a p-values vs. bayes factors argument. The tedium of this argument (there really aren't good reasons to prefer p-values) may even give out the impression that BDA is tedious and limited to model comparison and hypothesis testing problems. It isn't! Bayes has benefits over frequentism that reach far beyond the p-vs-bf issue.

Here's a practical example: It is well known that estimating generalized linear mixed models is kind of difficult. In fact, maximum likelihood methods routinely fail, especially when data are sparse of parameters are plenty (you've heard of multilevel models not converging, right? That's the issue.). However, bayesian methods (via MCMC for example) usually have no problem estimating these models in situations when maximum likelihood fails! This benefit of bayes over frequentism (only the first thing to come to mind) doesn't usually appear in the tedious p-vs-bf arguments, although one could argue that its practical implications are greater.
    
# Reasons for thinking that BDA is BF
    
I suspect that one factor contributing to the apparent conflation of BDA and BFs is that there are vocal groups of psychological scientists doing interesting and important work promoting the use of Bayes Factors for hypothesis testing, and bayesian methods more generally (eg. Dienes, 2015; Ly, Verhagen, & Wagenmakers, 2015; Morey, Romeijn, & Rouder, 2016; Rouder, Morey, Verhagen, Province, & Wagenmakers, 2016). A quick reading of some of these texts may give the (false) impression that bayes factors are a larger portion of BDA than what they actually are. I think the same goes with the APS Observer columns mentioned above. To be completely clear, these papers are not about, nor do they say, that BDA is BF. I'm merely pointing out that in the psychological literature, (important!) papers about bayesian methods focusing on BF vastly overshadow in number papers that discuss other features of BDA.

But the real root cause for this conflation is probably the fetish-like desire of hypothesis tests in psychological science. 

# A modest proposal

If now is the time to move toward a new statistical paradigm in psychology, we could take the opportunity to emphasize not only bayesian hypothesis testing, but the importance of modeling, estimation and bayesian methods more generally. As Dr. Andrews [noted](https://youtu.be/_gAg9UG9RCA), BDA could instead be thought of as flexible probabilistic modeling. 

[^note]: To be sure, I think a bayes factor can be a truly great tool when the competing models are well specified. I haven't yet implemented a bayes factor method for my bayesian multilevel mediation package (Vuorre & Bolger, 2017), but might include one in the future. One difficulty here is specifying the competing models in a meaningful way.

# References

<div class="csl-bib-body" style="line-height: 2; padding-left: 2em; text-indent:-2em;">
  <div class="csl-entry">Dienes, Z. (2015). How Bayes factors change scientific practice. <i>Journal of Mathematical Psychology</i>. https://doi.org/10.1016/j.jmp.2015.10.003</div>
  <span class="Z3988" title="url_ver=Z39.88-2004&amp;ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fzotero.org%3A2&amp;rft_id=info%3Adoi%2F10.1016%2Fj.jmp.2015.10.003&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&amp;rft.genre=article&amp;rft.atitle=How%20Bayes%20factors%20change%20scientific%20practice&amp;rft.jtitle=Journal%20of%20Mathematical%20Psychology&amp;rft.stitle=Journal%20of%20Mathematical%20Psychology&amp;rft.aufirst=Zoltan&amp;rft.aulast=Dienes&amp;rft.au=Zoltan%20Dienes&amp;rft.date=2015&amp;rft.issn=0022-2496"></span>
  <div class="csl-entry">Gallistel, C. R. (2015a). Bayes for Beginners 2: The Prior. <i>APS Observer</i>, <i>28</i>(8). Retrieved from https://www.psychologicalscience.org/observer/bayes-for-beginners-2-the-prior</div>
  <span class="Z3988" title="url_ver=Z39.88-2004&amp;ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fzotero.org%3A2&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&amp;rft.genre=article&amp;rft.atitle=Bayes%20for%20Beginners%202%3A%20The%20Prior&amp;rft.jtitle=APS%20Observer&amp;rft.volume=28&amp;rft.issue=8&amp;rft.aufirst=C.%20Randy&amp;rft.aulast=Gallistel&amp;rft.au=C.%20Randy%20Gallistel&amp;rft.date=2015-09-30"></span>
  <div class="csl-entry">Gallistel, C. R. (2015b). Bayes for Beginners 3: The Prior in Probabilistic Inference. <i>APS Observer</i>, <i>28</i>(9). Retrieved from https://www.psychologicalscience.org/observer/bayes-for-beginners-3-the-prior-in-probabilistic-inference</div>
  <span class="Z3988" title="url_ver=Z39.88-2004&amp;ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fzotero.org%3A2&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&amp;rft.genre=article&amp;rft.atitle=Bayes%20for%20Beginners%203%3A%20The%20Prior%20in%20Probabilistic%20Inference&amp;rft.jtitle=APS%20Observer&amp;rft.volume=28&amp;rft.issue=9&amp;rft.aufirst=C.%20Randy&amp;rft.aulast=Gallistel&amp;rft.au=C.%20Randy%20Gallistel&amp;rft.date=2015-10-30"></span>
  <div class="csl-entry">Gallistel, C. R. (2015c). Bayes for Beginners: Probability and Likelihood. <i>APS Observer</i>, <i>28</i>(7). Retrieved from https://www.psychologicalscience.org/observer/bayes-for-beginners-probability-and-likelihood</div>
  <span class="Z3988" title="url_ver=Z39.88-2004&amp;ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fzotero.org%3A2&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&amp;rft.genre=article&amp;rft.atitle=Bayes%20for%20Beginners%3A%20Probability%20and%20Likelihood&amp;rft.jtitle=APS%20Observer&amp;rft.volume=28&amp;rft.issue=7&amp;rft.aufirst=C.%20Randy&amp;rft.aulast=Gallistel&amp;rft.au=C.%20Randy%20Gallistel&amp;rft.date=2015-08-31"></span>
  <div class="csl-entry">Gelman, A., Carlin, J. B., Stern, H. S., Dunson, D. B., Vehtari, A., &amp; Rubin, D. B. (2013). <i>Bayesian Data Analysis, Third Edition</i>. Boca Raton: Chapman and Hall/CRC.</div>
  <span class="Z3988" title="url_ver=Z39.88-2004&amp;ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fzotero.org%3A2&amp;rft_id=urn%3Aisbn%3A978-1-4398-4095-5&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=book&amp;rft.btitle=Bayesian%20Data%20Analysis%2C%20Third%20Edition&amp;rft.place=Boca%20Raton&amp;rft.publisher=Chapman%20and%20Hall%2FCRC&amp;rft.aufirst=Andrew&amp;rft.aulast=Gelman&amp;rft.au=Andrew%20Gelman&amp;rft.au=John%20B.%20Carlin&amp;rft.au=Hal%20S.%20Stern&amp;rft.au=David%20B.%20Dunson&amp;rft.au=Aki%20Vehtari&amp;rft.au=Donald%20B.%20Rubin&amp;rft.date=2013-11-01&amp;rft.tpages=677&amp;rft.isbn=978-1-4398-4095-5&amp;rft.language=en"></span>
  <div class="csl-entry">Ly, A., Verhagen, J., &amp; Wagenmakers, E.-J. (2015). Harold Jeffreys’s default Bayes factor hypothesis tests: Explanation, extension, and application in psychology. <i>Journal of Mathematical Psychology</i>. https://doi.org/10.1016/j.jmp.2015.06.004</div>
  <span class="Z3988" title="url_ver=Z39.88-2004&amp;ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fzotero.org%3A2&amp;rft_id=info%3Adoi%2F10.1016%2Fj.jmp.2015.06.004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&amp;rft.genre=article&amp;rft.atitle=Harold%20Jeffreys%E2%80%99s%20default%20Bayes%20factor%20hypothesis%20tests%3A%20Explanation%2C%20extension%2C%20and%20application%20in%20psychology&amp;rft.jtitle=Journal%20of%20Mathematical%20Psychology&amp;rft.stitle=Journal%20of%20Mathematical%20Psychology&amp;rft.aufirst=Alexander&amp;rft.aulast=Ly&amp;rft.au=Alexander%20Ly&amp;rft.au=Josine%20Verhagen&amp;rft.au=Eric-Jan%20Wagenmakers&amp;rft.date=2015&amp;rft.issn=0022-2496"></span>
  <div class="csl-entry">McElreath, R. (2016). <i>Statistical Rethinking: A Bayesian Course with Examples in R and Stan</i>. CRC Press.</div>
  <span class="Z3988" title="url_ver=Z39.88-2004&amp;ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fzotero.org%3A2&amp;rft_id=urn%3Aisbn%3A978-1-4822-5346-7&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=book&amp;rft.btitle=Statistical%20Rethinking%3A%20A%20Bayesian%20Course%20with%20Examples%20in%20R%20and%20Stan&amp;rft.publisher=CRC%20Press&amp;rft.aufirst=Richard&amp;rft.aulast=McElreath&amp;rft.au=Richard%20McElreath&amp;rft.date=2016-01-05&amp;rft.tpages=485&amp;rft.isbn=978-1-4822-5346-7&amp;rft.language=en"></span>
  <div class="csl-entry">Morey, R. D., Romeijn, J.-W., &amp; Rouder, J. N. (2016). The philosophy of Bayes factors and the quantification of statistical evidence. <i>Journal of Mathematical Psychology</i>. https://doi.org/10.1016/j.jmp.2015.11.001</div>
  <span class="Z3988" title="url_ver=Z39.88-2004&amp;ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fzotero.org%3A2&amp;rft_id=info%3Adoi%2F10.1016%2Fj.jmp.2015.11.001&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&amp;rft.genre=article&amp;rft.atitle=The%20philosophy%20of%20Bayes%20factors%20and%20the%20quantification%20of%20statistical%20evidence&amp;rft.jtitle=Journal%20of%20Mathematical%20Psychology&amp;rft.stitle=Journal%20of%20Mathematical%20Psychology&amp;rft.aufirst=Richard%20D.&amp;rft.aulast=Morey&amp;rft.au=Richard%20D.%20Morey&amp;rft.au=Jan-Willem%20Romeijn&amp;rft.au=Jeffrey%20N.%20Rouder&amp;rft.date=2016&amp;rft.issn=0022-2496"></span>
  <div class="csl-entry">Rouder, J. N., Morey, R. D., Verhagen, J., Province, J. M., &amp; Wagenmakers, E.-J. (2016). Is There a Free Lunch in Inference? <i>Topics in Cognitive Science</i>, <i>8</i>(3), 520–547. https://doi.org/10.1111/tops.12214</div>
  <span class="Z3988" title="url_ver=Z39.88-2004&amp;ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fzotero.org%3A2&amp;rft_id=info%3Adoi%2F10.1111%2Ftops.12214&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&amp;rft.genre=article&amp;rft.atitle=Is%20There%20a%20Free%20Lunch%20in%20Inference%3F&amp;rft.jtitle=Topics%20in%20Cognitive%20Science&amp;rft.stitle=Top%20Cogn%20Sci&amp;rft.volume=8&amp;rft.issue=3&amp;rft.aufirst=Jeffrey%20N.&amp;rft.aulast=Rouder&amp;rft.au=Jeffrey%20N.%20Rouder&amp;rft.au=Richard%20D.%20Morey&amp;rft.au=Josine%20Verhagen&amp;rft.au=Jordan%20M.%20Province&amp;rft.au=Eric-Jan%20Wagenmakers&amp;rft.date=2016-07-01&amp;rft.pages=520-547&amp;rft.spage=520&amp;rft.epage=547&amp;rft.issn=1756-8765&amp;rft.language=en"></span>
  <div class="csl-entry">Vuorre, M. (2016, August 23). Statistical inference: Prix fixe or à la carte? Retrieved 4 May 2017, from https://mvuorre.github.io/post/2016/2016-08-23-free-lunch-in-inference/</div>
  <span class="Z3988" title="url_ver=Z39.88-2004&amp;ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fzotero.org%3A2&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Adc&amp;rft.type=webpage&amp;rft.title=Statistical%20inference%3A%20Prix%20fixe%20or%20%C3%A0%20la%20carte%3F&amp;rft.description=Experimental%20investigations%20commonly%20begin%20with%20a%20hypothesis%2C%20an%20expectation%20of%20what%20one%20might%20find%3A%20%E2%80%9CWe%20hypothesize%20that%20alcohol%20leads%20to%20slower%20reactions%20to%20events%20in%20a%20driving%20simulator.%E2%80%9D%20Data%20is%20then%20collected%20and%20analyzed%20to%20specifically%20address%20this%20hypothesis.%20Almost%20always%2C%20the%20support%20for%20or%20against%20the%20hypothesis%20is%20statistical%2C%20not%20intraocular%20(Krantz%2C%201999).%20However%2C%20the%20prevailing%20statistical%20paradigm%E2%80%94null%20hypothesis%20significance%20testing%20(NHST)%E2%80%94never%20tests%20the%20researcher%E2%80%99s%20offered%20hypothesis%2C%20but%20instead%20the%20%E2%80%9Cnull%20hypothesis%E2%80%9D%3A%20That%20there%20is%20no%20relationship%20between%20alcohol%20consumption%20and%20reaction%20time.%20NHST%20results%20in%20a%20p-value%2C%20and%20values%20of%20p%20less%20than%20.05%20are%20taken%20to%20indicate%20indicate%20that%20the%20data%20are%20sufficiently%20surprising%20under%20the%20null%20hypothesis%20that%20we%20now%20must%20accept%20the%20alternative%20hypothesis.&amp;rft.identifier=https%3A%2F%2Fmvuorre.github.io%2Fpost%2F2016%2F2016-08-23-free-lunch-in-inference%2F&amp;rft.aufirst=Matti&amp;rft.aulast=Vuorre&amp;rft.au=Matti%20Vuorre&amp;rft.date=2016-08-23"></span>
  <div class="csl-entry">Vuorre, M., &amp; Bolger, N. (2017). Within-subject mediation analysis for experimental data in cognitive psychology and neuroscience. <i>OSF Preprint</i>. https://doi.org/http://dx.doi.org/10.17605/OSF.IO/6JHPF</div>
  <span class="Z3988" title="url_ver=Z39.88-2004&amp;ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fzotero.org%3A2&amp;rft_id=info%3Adoi%2Fhttp%3A%2F%2Fdx.doi.org%2F10.17605%2FOSF.IO%2F6JHPF&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&amp;rft.genre=article&amp;rft.atitle=Within-subject%20mediation%20analysis%20for%20experimental%20data%20in%20cognitive%20psychology%20and%20neuroscience&amp;rft.jtitle=OSF%20Preprint&amp;rft.aufirst=Matti&amp;rft.aulast=Vuorre&amp;rft.au=Matti%20Vuorre&amp;rft.au=Niall%20Bolger&amp;rft.date=2017"></span>
</div>

