---
title: 'rpihkal: Stop pasting and start gluing'
author: Matti Vuorre
date: '2018-12-12'
slug: rpihkal-stop-pasting-and-start-gluing
categories:
  - data science
tags:
  - R
  - rpihkal
image:
  caption: ''
  focal_point: ''
subtitle: 'Use the glue R package to join strings.'
output:
  blogdown::html_page:
    toc: yes
    number_sections: no
    toc_depth: 2
    df_print: paged
summary: 'How to use the glue R package to join strings.'
bibliography: "/Users/Matti/Documents/vuorre.netlify.com/static/bibliography/blog.bib"
---

<link href="/rmarkdown-libs/pagedtable/css/pagedtable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/pagedtable/js/pagedtable.js"></script>

<div id="TOC">
<ul>
<li><a href="#paste">Paste</a></li>
<li><a href="#glue">Glue</a></li>
<li><a href="#appendix-papaja">Appendix: papaja</a></li>
</ul>
</div>

<p>We’ve all been there; writing <a href="https://github.com/crsh/papaja">manuscripts</a> with <a href="https://rmarkdown.rstudio.com/">R Markdown</a> and dreaming of easy in-text code bits for reproducible reporting. Say you’ve fit a regression model to your data, and would then like to report the model’s parameters in your text, without writing the values in the text. (If the data or model changes, you’d need to re-type the values again.)</p>
<p>For example, you can print this model summary easily in the R console:</p>
<pre class="r"><code>fit &lt;- lm(mpg ~ disp, data = mtcars)
summary(fit)</code></pre>
<pre><code>## 
## Call:
## lm(formula = mpg ~ disp, data = mtcars)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.8922 -2.2022 -0.9631  1.6272  7.2305 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 29.599855   1.229720  24.070  &lt; 2e-16 ***
## disp        -0.041215   0.004712  -8.747 9.38e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.251 on 30 degrees of freedom
## Multiple R-squared:  0.7183, Adjusted R-squared:  0.709 
## F-statistic: 76.51 on 1 and 30 DF,  p-value: 9.38e-10</code></pre>
<p>And to cite those values in the text body of your manuscript, you can write the text in R Markdown like this:</p>
<pre class="r"><code>The model intercept was `r round(coef(fit)[1], 2)`, great.</code></pre>
<p>Which would show up in your manuscript like this:</p>
<p>The model intercept was 29.6, great.</p>
<div id="paste" class="section level2">
<h2>Paste</h2>
<p>However, when you want to present more information, such as the parameter estimate with its standard error, you will have to <code>paste()</code> those strings together:</p>
<pre class="r"><code>(x &lt;- round(summary(fit)$coefficients, 3))</code></pre>
<pre><code>##             Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)   29.600      1.230  24.070        0
## disp          -0.041      0.005  -8.747        0</code></pre>
<pre class="r"><code>intercept &lt;- paste(&quot;b = &quot;, x[1, 1], &quot;, SE = &quot;, x[1, 2], sep = &quot;&quot;)</code></pre>
<p>You can then just cite the <code>intercept</code> object in your text body:</p>
<pre class="r"><code>The model intercept was very very significant (`r intercept`).</code></pre>
<p>Which would render in your PDF or word document as:</p>
<p>The model intercept was very very significant (b = 29.6, SE = 1.23).</p>
<p><code>paste()</code> is a base R function, and as such very robust and reproducible–all R installations will have it. However, as such it has a fairly terrible syntax where you have to quote strings, separate strings and variables with commas, etc. This task is made much easier with <code>glue()</code>.</p>
</div>
<div id="glue" class="section level2">
<h2>Glue</h2>
<p><a href="https://glue.tidyverse.org/">glue</a> is a small R package that allows you to join strings together in a neat, pythonific way. It replaces the need for quoting and separating arguments in <code>paste()</code>, by asking you to wrap variables in curly braces. Here’s how to do the above pasting with glue:</p>
<pre class="r"><code>library(glue)
intercept &lt;- glue(&quot;b = {x[1, 1]}, SE = {x[1, 2]}&quot;)</code></pre>
<p>Which gives you the same string as the much messier <code>paste()</code> approach: b = 29.6, SE = 1.23</p>
<div id="glue-with-data-frames" class="section level3">
<h3>Glue with data frames</h3>
<p>Glue has other neat (more advanced) features, such as gluing variables row-by-row in a data frame:</p>
<pre class="r"><code>library(dplyr)
as.data.frame(x) %&gt;% 
  glue_data(
    &quot;{rownames(.)}&#39;s point estimate was {Estimate}, with an SE of {`Std. Error`}.&quot;
  )</code></pre>
<pre><code>## (Intercept)&#39;s point estimate was 29.6, with an SE of 1.23.
## disp&#39;s point estimate was -0.041, with an SE of 0.005.</code></pre>
</div>
</div>
<div id="appendix-papaja" class="section level2">
<h2>Appendix: papaja</h2>
<p>For some models (like our simple linear model example here), the <a href="https://github.com/crsh/papaja">papaja R package</a> (which deserves its own rpihkal post!) has very useful shortcuts</p>
<pre class="r"><code>library(papaja)
intercept &lt;- apa_print(fit)$estimate$Intercept</code></pre>
<p>If you now cite <code>intercept</code> in the text body of your manuscript, it renders into <span class="math inline">\(\LaTeX\)</span> (which is interpreted nicely if you are outputting PDF or Word documents; here on this website it looks odd):</p>
<pre class="r"><code>The model intercept was rather significant (`r intercept`).</code></pre>
<p>The model intercept was rather significant (<span class="math inline">\(b = 29.60\)</span>, 95% CI <span class="math inline">\([27.09\)</span>, <span class="math inline">\(32.11]\)</span>).</p>
<p>Read more about glue at <a href="https://glue.tidyverse.org/" class="uri">https://glue.tidyverse.org/</a>.</p>
</div>
