---
title: "Mind Matters"
author: "Matti Vuorre"
date: 2014-06-02
categories: ["psychology"]
tags: ["publication"]
---

I recently wrote a piece for Scientific American's [mind matters][1] section. I wanted to call it "Why you won't believe me", but the editors thought otherwise. The post was about some cool [research][3] about how your name might influence how other people perceive your claims. It turns out that people are more likely to agree with people whose names they find easier to pronounce.

Anyway, I enjoyed writing for them, so hopefully you'll enjoy reading [the piece][2]:

> The results from these experiments showed that people with easier to pronounce names were judged as more familiar, less risky and less dangerous than individuals with difficult to pronounce names. So, who would you pick as your tandem skydiving partner, Bodo or Czeslaw? If you are anything like most English speaking people, you would be likely to prefer jumping out of the plane with Bodo. If, on the other hand, you find Polish easier to pronounce, you would probably choose to jump with Czeslaw.

While you're at it, why not take a look at the original [research article][3]. The authors even posted their raw data online, for those interested in additional analyses.

I also enjoyed the readers' thoughtful comments:

> This is (an example of) why I distrust most social research.

> This is why I believe people like [previous author] are scientifically illiterate.

[1]: http://www.scientificamerican.com/section/mind-matters/
[2]: http://www.scientificamerican.com/article/what-your-name-says-about-how-believable-you-are/
[3]: http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0088671
